spring:
  datasource:
#    jndi-name: jdbc/MDTDS
     
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.88.25.37:3306/mdt_data?rewriteBatchedStatements=true&useSSL=false
    username: magento
    password: password

server:
    port: 8084

mybatis:
  type-aliases-package: web.domain
